services:
  simpleserver:
    build: coreserver
    ports:
      - '55986:5986'
    tty: true
    container_name: simpleserver
  client:
    build: coreserver
    ports:
      - '55987:5986'
    tty: true
    container_name: client