---
networks:
  chocolab:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  chocoserver:
    build: chocolateyserver
    container_name: chocoserver
    environment:
      - DOCKER=true
    hostname: chocoserver
    networks:
      chocolab:
        ipv4_address: 172.20.0.10
      dns:
        - 8.8.8.8
        - 8.8.4.4
    ports:
      - '55986:5986'
      - '13900:139'
      - '8080:80'
    tty: true
  client:
    build: client
    container_name: client
    environment:
      - DOCKER=true
    hostname: client
    networks:
      chocolab:
        ipv4_address: 172.20.0.11
      dns:
        - 8.8.8.8
        - 8.8.4.4
    ports:
      - '55987:5986'
    tty: true
