---
networks:
  chocolab:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  chocoserver:
    build: coreserver
    container_name: chocoserver
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DOCKER=true
    hostname: chocoserver
    networks:
      chocolab:
        ipv4_address: 172.20.0.10
    ports:
<<<<<<< HEAD
      - "55986:5986"
      - "13900:139"
      - "8080:80"
    tty: true
  client:
    build: client
=======
      - '55986:5986'
      - '13900:139'
      - '8080:80'
    tty: true
  client:
    build: coreserver
>>>>>>> acbbbc325e67409514a97a1f0f77acccfd12846b
    container_name: client
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DOCKER=true
    hostname: client
    networks:
      chocolab:
        ipv4_address: 172.20.0.11
    ports:
<<<<<<< HEAD
      - "55987:5986"
    tty: true
=======
      - '55987:5986'
    tty: true
>>>>>>> acbbbc325e67409514a97a1f0f77acccfd12846b
