networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  chocoserver:
    build: chocolateyserver
    ports:
      - '55986:5986'
      - '13900:139'
      - '8080:80'
    hostname: chocoserver
    networks:
      mynetwork:
        ipv4_address: 172.20.0.10
    environment: 
      - DOCKER=true
    tty: true
    container_name: chocoserver
  client:
    build: client
    ports:
      - '55987:5986'
    container_name: client
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11
    environment: 
      - DOCKER=true
    tty: true
